### ISSUE TITLE
Timer enhancement ideas

### ISSUE THREAD

**Issue by wezm** [race604/clock-tui#1]
I checked out a bunch of clock/timer tools and this one looks really good. I had some ideas for the timer that might be interesting:

- [x] Allow the fractional seconds to be disabled (they can be a bit distracting).
- [x] When the timer ends make it blink, perhaps in a different colour.
- [x] Accept a command to run when the timer ends. This could be used to invoke `notify-send` to show a notification when the timer ends
  - E.g `tclock timer -d 14m -e notify-send 'Timer' 'The timer has finished'`

**Comment by race604** [comment]
Hi @wezm, thanks for your interest on this tool, and those ideas sounds really great. I'll try to support those features, and pull requests are welcome if you want to help implement them.

**Comment by race604** [comment]
All features are implemented, and included in version 0.3.0+.

Thank Wezm for the contribution!

**Comment by wezm** [comment]
Fantastic, thank you.
