### ISSUE TITLE
[Feature request] Option to quit after timer ends

### ISSUE THREAD

**Issue by skygate2012** [race604/clock-tui#26]
First of all, thank you so much for such a neat but gorgeous tui clock program. I've been writing my own not nearly as good.
It would be great to add a parameter perhaps, for it to quit after timer (or countdown also) completes. I'm integrating this into my workflow scripts.

**Comment by race604** [comment]
Thanks for your interest on this tool. And the quit-option is great idea, I submit a commit [f616555](https://github.com/race604/clock-tui/commit/f616555fa2e0019eb0099f393f068167d4a97f82) that implemented this feature, you can take try, thanks for your suggestion.
