### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by wezm** [race604/clock-tui#7]
Hi I would like to create an [AUR](https://wiki.archlinux.org/title/Arch_User_Repository) package for clock-tui. To do so it's preferred to be able to package versioned releases. Would it be possible for you to create [git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) and/or [GitHub releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) for each new version in order to facilitate this?

**Comment by race604** [comment]
Great suggestion, the releases are here now https://github.com/race604/clock-tui/releases.

**Comment by wezm** [comment]
Awesome, thanks

**Comment by wezm** [comment]
Sorry to keep hassling you. Might be good to add a `LICENCE` file too.

**Comment by wezm** [comment]
AUR package is up now too: https://aur.archlinux.org/packages/clock-tui

**Comment by race604** [comment]
Not at all, thank you for helping the project become more standardized.
LICENSE file is added, and I will create a new release latter.
